# Generated by Django 3.2.12 on 2022-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField(help_text='反馈内容', verbose_name='反馈内容')),
                ('choose', models.IntegerField(default=0, help_text='解决状态,1:已解决;0:未解决', verbose_name='解决状态')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReplys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(help_text='回复问题', verbose_name='回复问题')),
            ],
        ),
    ]
