# Generated by Django 3.2.12 on 2022-06-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('feedbackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreplys',
            name='accept_user',
            field=models.ForeignKey(help_text='受理人id', on_delete=django.db.models.deletion.CASCADE, related_name='UserDetail2', to='login.userdetail', verbose_name='受理人id'),
        ),
        migrations.AddField(
            model_name='feedbackreplys',
            name='father_reply',
            field=models.ForeignKey(help_text='父回复id', on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.feedbackreplys', verbose_name='父回复id'),
        ),
        migrations.AddField(
            model_name='feedbackreplys',
            name='feedback',
            field=models.ForeignKey(help_text='反馈问题id', on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.feedback', verbose_name='反馈问题id'),
        ),
        migrations.AddField(
            model_name='feedbackreplys',
            name='user_id',
            field=models.ForeignKey(help_text='反馈人id', on_delete=django.db.models.deletion.CASCADE, to='login.userdetail', verbose_name='反馈人id'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_user',
            field=models.ForeignKey(help_text='反馈人id', on_delete=django.db.models.deletion.CASCADE, to='login.userdetail', verbose_name='反馈人id'),
        ),
    ]
