# Generated by Django 3.2.12 on 2022-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(default=0, help_text='手机号码', verbose_name='手机号码'),
        ),
    ]
