# Generated by Django 3.2.12 on 2022-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default='', help_text='用户名', max_length=10, unique=True, verbose_name='用户名'),
        ),
    ]
