# Generated by Django 3.2.12 on 2022-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='', help_text='密码', max_length=18, verbose_name='密码'),
        ),
    ]
