# Generated by Django 3.2.12 on 2022-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userdetail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='邮箱', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(default='', help_text='手机号码', max_length=30, verbose_name='手机号码'),
        ),
    ]
