# Generated by Django 3.2.12 on 2022-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20220608_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱', max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(help_text='手机号码', max_length=30, unique=True, verbose_name='手机号码'),
        ),
    ]
