# Generated by Django 3.2.12 on 2022-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20220609_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='', help_text='密码', max_length=255, verbose_name='密码'),
        ),
    ]
