# Generated by Django 3.2.12 on 2022-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_userdetail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='icon',
            field=models.ImageField(default='icon/default.png', upload_to='icon'),
        ),
    ]
