# Generated by Django 3.2.12 on 2022-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_userdetail_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='icon',
            field=models.ImageField(default='icon/default.png', upload_to='media/icon'),
        ),
    ]
